version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  inbound-thirdparty-scheme-adapter:
    container_name: inbound-thirdparty-scheme-adapter
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    command: sh -c "/opt/thirdparty-scheme-adapter/wait4/wait4.js inbound-thirdparty-scheme-adapter && NODE_ENV=integration npm run start:inbound"
    volumes:
      - ./docker/wait4:/opt/thirdparty-scheme-adapter/wait4
    environment:
      - NODE_ENV=integration
    networks:
      - mojaloop-net
    ports:
      - "4005:4005"
    depends_on:
      - redis
    extra_hosts:
      - "redis:172.17.0.1"
      - "ml-testing-toolkit:172.17.0.1"
    healthcheck:
      test: wget -q http://172.17.0.1:4005/health -O /dev/null || exit 1
      timeout: 3s
      retries: 10
      start_period: 10s
      interval: 30s

  outbound-thirdparty-scheme-adapter:
    container_name: outbound-thirdparty-scheme-adapter
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    command: sh -c "/opt/thirdparty-scheme-adapter/wait4/wait4.js outbound-thirdparty-scheme-adapter && NODE_ENV=integration npm run start:outbound"
    volumes:
      - ./docker/wait4:/opt/thirdparty-scheme-adapter/wait4
    environment:
      - NODE_ENV=integration
    networks:
      - mojaloop-net
    ports:
      - "4006:4006"
    depends_on:
      - redis
    extra_hosts:
      - "redis:172.17.0.1"
      - "ml-testing-toolkit:172.17.0.1"
      - "sdk-scheme-adapter:172.17.0.1"
    healthcheck:
      test: wget -q http://172.17.0.1:4006/health -O /dev/null || exit 1
      timeout: 3s
      retries: 10
      start_period: 10s
      interval: 30s
  
  sdk-scheme-adapter:
    image: "mojaloop/sdk-scheme-adapter:v11.11.3"
    container_name: sdk-scheme-adapter
    env_file: ./docker/sdk_scheme_adapter.env
    volumes:
      - "./docker/secrets:/secrets"
      - "./docker/jwsVerificationKeys:/jwsVerificationKeys"
    ports:
      - "7000:4000"
      - "7002:4001"
    networks:
      - mojaloop-net
    depends_on:
      - redis
    restart: always
    extra_hosts:
      - "central-ledger.local:172.17.0.1"
      - "central-settlement.local:172.17.0.1"
      - "ml-api-adapter.local:172.17.0.1"
      - "account-lookup-service.local:172.17.0.1"
      - "account-lookup-service-admin.local:172.17.0.1"
      - "quoting-service.local:172.17.0.1"
      - "moja-simulator.local:172.17.0.1"
      - "central-ledger:172.17.0.1"
      - "central-settlement:172.17.0.1"
      - "ml-api-adapter:172.17.0.1"
      - "account-lookup-service:172.17.0.1"
      - "account-lookup-service-admin:172.17.0.1"
      - "quoting-service:172.17.0.1"
      - "simulator:172.17.0.1"
      - "host.docker.internal:172.17.0.1"
      - "simulator.local:172.17.0.1"
      - "transaction-request-service:172.17.0.1"
      - "pisp-backend:172.17.0.1"
      - "ml-testing-toolkit:172.17.0.1"


  redis:
    container_name: redis
    image: "redis:6.0.10-alpine"
    networks:
      - mojaloop-net
    ports:
      - "6379:6379"
    restart: always