version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  inbound-thirdparty-scheme-adapter-a:
    container_name: inbound-thirdparty-scheme-adapter-a
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: sh -c "/opt/thirdparty-scheme-adapter/wait4/wait4.js inbound-thirdparty-scheme-adapter && NODE_ENV=integration npm run start:inbound"
    volumes:
      - ./wait4:/opt/thirdparty-scheme-adapter/wait4
      - ./scheme_a/config:/opt/thirdparty-scheme-adapter/config
    environment:
      - NODE_ENV=integration
    networks:
      - mojaloop-net
    ports:
      - "4055:4055"
    depends_on:
      - pisp-simulator
    extra_hosts:
      - "redis:172.17.0.1"
      - "pisp-simulator:172.17.0.1"
    healthcheck:
      test: wget -q http://172.17.0.1:4055/health -O /dev/null || exit 1
      timeout: 3s
      retries: 10
      start_period: 10s
      interval: 30s

  outbound-thirdparty-scheme-adapter-a:
    container_name: outbound-thirdparty-scheme-adapter-a
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: sh -c "/opt/thirdparty-scheme-adapter/wait4/wait4.js outbound-thirdparty-scheme-adapter && NODE_ENV=integration npm run start:outbound"
    volumes:
      - ./wait4:/opt/thirdparty-scheme-adapter/wait4
      - ./scheme_a/config:/opt/thirdparty-scheme-adapter/config
    environment:
      - NODE_ENV=integration
    networks:
      - mojaloop-net
    ports:
      - "4056:4056"
    depends_on:
      - pisp-simulator
    extra_hosts:
      - "redis:172.17.0.1"
      - "pisp-simulator:172.17.0.1"
    healthcheck:
      test: wget -q http://172.17.0.1:4056/health -O /dev/null || exit 1
      timeout: 3s
      retries: 10
      start_period: 10s
      interval: 30s
  
  inbound-thirdparty-scheme-adapter-b:
    container_name: inbound-thirdparty-scheme-adapter-b
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: sh -c "/opt/thirdparty-scheme-adapter/wait4/wait4.js inbound-thirdparty-scheme-adapter && NODE_ENV=integration npm run start:inbound"
    volumes:
      - ./wait4:/opt/thirdparty-scheme-adapter/wait4
      - ./scheme_b/config:/opt/thirdparty-scheme-adapter/config
    environment:
      - NODE_ENV=integration
    networks:
      - mojaloop-net
    ports:
      - "4057:4057"
    depends_on:
      - pisp-simulator
    extra_hosts:
      - "redis:172.17.0.1"
      - "pisp-simulator:172.17.0.1"
    healthcheck:
      test: wget -q http://172.17.0.1:4057/health -O /dev/null || exit 1
      timeout: 3s
      retries: 10
      start_period: 10s
      interval: 30s

  outbound-thirdparty-scheme-adapter-b:
    container_name: outbound-thirdparty-scheme-adapter-b
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: sh -c "/opt/thirdparty-scheme-adapter/wait4/wait4.js outbound-thirdparty-scheme-adapter && NODE_ENV=integration npm run start:outbound"
    volumes:
      - ./wait4:/opt/thirdparty-scheme-adapter/wait4
      - ./scheme_b/config:/opt/thirdparty-scheme-adapter/config
    environment:
      - NODE_ENV=integration
    networks:
      - mojaloop-net
    ports:
      - "4058:4058"
    depends_on:
      - pisp-simulator
    extra_hosts:
      - "redis:172.17.0.1"
      - "pisp-simulator:172.17.0.1"
    healthcheck:
      test: wget -q http://172.17.0.1:4058/health -O /dev/null || exit 1
      timeout: 3s
      retries: 10
      start_period: 10s
      interval: 30s

  pisp-simulator:
    image: mojaloop/mojaloop-simulator:v11.3.0.2-pisp
   # build: 
   #   context: .././mojaloop-simulator
    networks:
      - mojaloop-net
    container_name: pisp-simulator
    env_file: ./dfsp_backend.env
    volumes:
       - ./dfsp_rules.json:/src/rules.json
    ports:
      - "9000:3000"
      - "9002:3002"
      - "9003:3003"    